import Head from 'next/head'
import React, { useState } from 'react'
import '../styles/css/globals.scss'
import { AppProps } from 'next/app'
import { store } from '../redux/store'
import { Provider } from 'react-redux'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { QueryClient, QueryClientProvider } from 'react-query'
import { ReactQueryDevtools } from "react-query/devtools"
import OneSignal from 'components/common/OneSignal/OneSignal'

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {

  const [queryClient] = useState<QueryClient>(() => new QueryClient({
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false,
        refetchOnMount: false,
        refetchOnReconnect: false,
        retry: false,
        staleTime: 1 * 60 * 1000,
      },
    },
  }));

  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}>
        <div className='root-app'>
          <Head>
            <title>Live Chat</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component pageProps={pageProps}></Component>
          <OneSignal />
        </div>
        <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
    </Provider>
  )
}

export default MyApp;
